services:
  config-service:
    image: 061039771220.dkr.ecr.ap-northeast-2.amazonaws.com/config-service
    container_name: config-service
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: always
    networks:
      - msa-network

  discovery-service:
    image: 061039771220.dkr.ecr.ap-northeast-2.amazonaws.com/discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
    networks:
      - msa-network

  gate-service:
    image: 061039771220.dkr.ecr.ap-northeast-2.amazonaws.com/gate-service
    container_name: gateway-service
    ports:
      - "8000:8000"
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    networks:
      - msa-network

  user-service:
    image: 061039771220.dkr.ecr.ap-northeast-2.amazonaws.com/user-service
    container_name: user-service
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    restart: always
    networks:
      - msa-network

  order-service:
    image: 061039771220.dkr.ecr.ap-northeast-2.amazonaws.com/user-service
    container_name: ordering-service
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    restart: always
    networks:
      - msa-network

  product-service:
    image: 061039771220.dkr.ecr.ap-northeast-2.amazonaws.com/product-service
    container_name: product-service
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    restart: always
    networks:
      - msa-network

  db:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: orderservice
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - msa-network

volumes:
  db-data:

networks:
  msa-network:
    driver: bridge
